name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        env:
          CYPRESS_VALID_EMAIL: ${{ secrets.CYPRESS_VALID_EMAIL }}
          CYPRESS_VALID_PASSWORD: ${{ secrets.CYPRESS_VALID_PASSWORD }}
        run: npx cypress run